# Generated by Django 2.1.1 on 2018-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '项目名称', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterField(
            model_name='product',
            name='productdesc',
            field=models.CharField(max_length=200, verbose_name='项目描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producter',
            field=models.CharField(max_length=200, verbose_name='项目负责人'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productname',
            field=models.CharField(max_length=64, verbose_name='项目名称'),
        ),
    ]
