# Generated by Django 2.1.1 on 2018-10-31 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20181031_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
