# Generated by Django 2.1.1 on 2018-10-31 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20181031_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '项目名称', 'verbose_name_plural': '项目名称'},
        ),
    ]
